// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY89zcNi_WiKDoE3E9gW7t05Ku3LT8_H8',
    appId: '1:720504682308:android:06d78680334f6df3dec911',
    messagingSenderId: '720504682308',
    projectId: 'care-for-elders',
    storageBucket: 'care-for-elders.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoHrFQjx414_iHDTfcN5nalmBNTI1tZi8',
    appId: '1:720504682308:ios:af82a5ce317d7c2cdec911',
    messagingSenderId: '720504682308',
    projectId: 'care-for-elders',
    storageBucket: 'care-for-elders.firebasestorage.app',
    iosBundleId: 'com.example.careForElders',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY89zcNi_WiKDoE3E9gW7t05Ku3LT8_H8',
    appId: '1:720504682308:web:06d78680334f6df3dec911',
    messagingSenderId: '720504682308',
    projectId: 'care-for-elders',
    authDomain: 'care-for-elders.firebaseapp.com',
    storageBucket: 'care-for-elders.firebasestorage.app',
  );
}
